services:
  db:
    image: postgres:18
    container_name: blog_db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: xxxxx
    ports:
      - "5432:5432"
    volumes:
      - blogdata:/var/lib/postgresql

volumes:
  blogdata:
